# @copyright (C) Syntacore 2017. All rights reserved.
# SCR sample apps
# Makefile

APP += mnist

APP_SRC += mnist.c neural_network.c fix16.c fix16_exp.c

INTERNAL_PRINTF=1

COMMON_BASE = common
include $(COMMON_BASE)/common.mk
