# @copyright (C) Syntacore 2017. All rights reserved.
# SCR sample apps
# Makefile

APP += sha256

APP_SRC += sha256.c

INTERNAL_PRINTF=1

COMMON_BASE = common
include $(COMMON_BASE)/common.mk
